% Artificial Bee Colony algorithm by Karaboga
% Project: DAE-855-MID
% Project Title: High temperature thermal contact conductance (TCC) 
% measurement for PT-CT contact
%
% Developer: Akshay Kumar Khandelwal
% Contact: akshay.kr.khandelwal@gmail.com

%% This is a file to generate data for ABC algorithm with assuming TCC as 2300
% The data is generated by solving governing equations through FDM
% The model is 1D with two objects of pure copper of length 30mm with given material
% properties. The boundary conditions are constant temperature condition at
% hot and cold end. The temperature data generated will then be used to
% determine efficacy of ABC algorithm

x1 = 0:0.001:0.030;                 % Nodes for upper specimen
dx1 = x1(2);                        % Differential element
x2 = 0:0.001:0.030;                 % Nodes for lower specimen
dx2 = x2(2);                        % Differential element
t = 0:0.001:100;                    % Time nodes
dt = t(2);                          % Differential time
TCC = 2120;                         % Highest limit for CFD to solve is 215000

% Material properties
k = 16;                             % Thermal Conductivity
c = 320;                            % Specific heat
rho = 8960;                         % Density
alpha = 4.09e-6;

% CFL condition
a = alpha*dt/(dx1^2);
if a > 0.5
    print('CFL Condition failed');
end

% Definition of solution matrix and boundary condition
T1 = zeros( length(x1), length(t)) + 25;
T2 = zeros( length(x2), length(t)) + 25;
T1( 1, :) = 300;
T1( :, 1) = 300;
T2( end, :) = 25;

%% Solution by FDM
for j = 1:length(t)-1
    % For upper specimen
    for i = 2:length(x1)-1
        T1( i, j+1) = a*( T1(i-1, j) - 2*T1( i, j) + T1( i+1, j)) + T1( i, j);
    end
    
    % For Nodes at interface
    T1( end, j+1) = T1( end - 1, j+1) - (TCC*dx1/k)*(T1( end, j) - T2( 1, j));
    T2( 1, j+1) = (TCC*dx1/k)*(T1( end, j) - T2( 1, j)) + T2( 2, j);
    
    % For Lower specimen
    for i = 2:length(x2)-1
        T2( i, j+1) = a*( T2(i-1, j) - 2*T2( i, j) + T2( i+1, j)) + T2( i, j);
    end
end
